addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: b70a0f3b-1785-4c65-adf9-bc6b64804127
after_success:
- ./df-build.sh
jdk:
- oraclejdk8
language: java
notifications: {}
# Modified by Insights Service at 2016-05-07 20:08:28.435176
